### PR TITLE
FRENCH language for New Private Message With Ajax extension

### PR DESCRIPTION
**Pull request by Galixte**
Hi @alg5,

before to merge, i want to know the answer for this: https://github.com/alg5/newpmajax/issues/2, to fix my translation, if it’s requiered.

### CODE REVIEW

**Comment by alg5** [comment]
thanks, merged

**Comment by Galixte** [comment]
Please read my message, i have to know the answer of my issue before because, according to the answer I would have again to edit files

**Comment by alg5** [comment]
sorry
https://github.com/alg5/newpmajax/issues/2

**Comment by Galixte** [comment]
ok i will update tonight, thanks.

**Comment by alg5** [comment]
I added one new langkey
    'PMAJAX_NO_SUCH_USER'                               => 'User %s not exists',
translate it please too

**Pull request merged**
